#Actividad 4
lista=['attccgt', 'agggggtttttcg','gtagc']
print (lista)
for i in range (3):
	print(len(lista[i]))

Actividad 5
secuencias=input("ingrese una secuencia de ADN")
for sentencias in range (3):
	print ("En la secuencia que usted ingreso se repite:",secuencias.count("n"),"veces las bases indefinidas")
	secuencias=input("ingrese una secuencia de ADN")

#Actividad 6
Sec2= 'GTTATAATATTGCTAAAATTATTCAGAGTAATATTGTGGATTAAAGCCACAATAAGATTTATAAATCTTAAATG ATGGGACTACCATCCTTACTCTCTCCATTTCAAGGCTGACGATAAGGAGACCTGCTTTGCCGAGGAGGTACTACA GTTCTCTTCACAAACAATTGTCTTACAAAATGAATAAAACAGCACTTTGTTTTTATCTCCTGCTTTTAATATGTC CAGTATTCATTTTTGCATGTTTGGTTAGGCTAGGGCTTAGGGATTTATATATCAAAGGAGGCTTTGTACATGTGG GACAGGGATCTTATTTTAGATTTATATATCAAAGGAGGCTTTGTACATGTGGGACAGGGATCTTATTTTACAAAC AATTGTCTTACAAAATGAATAAAACAGCACTTTGTTTTTATCTCCTGCTCTATTGTGCCATACTGTTGAATGTTT ATAATGCATGTTCTGTTTCCAAATTTCATGAAATCAAAACATTAATTTATTTAAACATTTACTTGAAATGTTCAC AAACAATTGTCTTACAAAATGAATAAAACAGCACTTTGTTTTTATCTCCTGCTTTTAATATGTCCAGTATTCATT TTTGCATGTTTGGTTAGGCTAGGGCTTAGGGATTTATATATCAAAGGAGGCTTTGTACATGTGGGACAGGGATCT TATTTTAGATTTATATATCAAAGGAGGCT'
Sec3= "ACTTTGTTTTTATCTCCTGCTCTATTGTGCCATACTGTTGAATGTTTATACCCTACATGGTGCATGTTCTGTTT CCAAATTTCATGAAATCAAAACATTAATTTATTTAAACATTTACTTGAAATGTTCACAAACAATTGTCTTACAAA ATGAATAAAACAGCACTTTGTTTTTATCTCCTGCTTTTAATATGTCCAGTATTCATTTTTGCATGTTTGGTTAGG CTAGGGCTTAGGGATTTATATATCAAAGGAGGCTTTGTACATGTGGGACAGGGATCTTATTTTAGATTTATATAT CAAAGGAGGCT"
total=Sec2.find("TATAAA",1)
print("La secuencia TATAAA fue encontrada en el caracter Nª",total,"En la primera secuencia")
total2=Sec3.find("TATAAA",1)
print("La secuencia TATAAA fue encontrada en el caracter Nª:", total2,"En la segunda secuencia")


